services:
  apache:
    image: httpd:latest
    container_name: dashboard
    restart: unless-stopped
    ports:
    - '80:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf