services:
  apache:
    image: nginx:latest
    container_name: dashboard
    restart: unless-stopped
    ports:
    - '80:80'
    volumes:
    - ./website:/var/www/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
