services:
  dashboard:
    image: nginx:latest
    container_name: dashboard
    network_mode: host
    restart: unless-stopped
    volumes:
    - ./website:/var/www/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
