server { 
 listen 80;
 server_name dashboard;
        location / {
          proxy_pass http://dashboard
        }

        location /flagwarehouse {
                return 301 $scheme://$host:5555/;
        }

        location /tulip {
                return 301 $scheme://$host:3000/;
        }
}
